### ISSUE TITLE
How to get username in AngularJS controller?

### ISSUE THREAD

**Issue by michaeljoser** [fnakstad/angular-client-side-auth#1]
Hi i really like your auth code and I am using it as a template for my project.

I was wondering what would be the best way to keep the username accessible through my custom Controllers.

I saw that I can use $rootScope.userRole to get the userRole in my controllers but what would be an efficient way to keep username?

i tried a UserDetails factory that keeps the username. it worked until i do a refresh of the page (F5) then i loose the username value.

any idea please?

**Comment by fnakstad** [comment]
Hi Michael,
I guess you could handle it in the same way as with the user role; just put the username in a cookie on the server-side when someone logs in, which you then can read into a $rootScope property when the Angular app has initialized. It's a pretty common use-case though, so I'll try to update my example with that functionality tomorrow. Thanks for the feedback!

**Comment by fnakstad** [comment]
I've updated the example to display username and indicate the role of the logged in user. You can check it out at: http://angular-client-side-auth.herokuapp.com/
I implemented it by setting a user cookie containing both username and role when a full page reload is requested. Furthermore, the login and register actions also return a user object of the same sort. Take a look at the code and example site, and let me know if something is unclear.

**Comment by michaeljoser** [comment]
that's super nice and really fits my needs. Cheers :)

**Comment by fnakstad** [comment]
No problem :) Good luck with your project!
