### ISSUE TITLE
Better handling of routingConfig

### ISSUE THREAD

**Issue by fnakstad** [fnakstad/angular-client-side-auth#10]
The way the `routingConfig` is utilized today smells a little bit... Maybe use `.constant()` to set `userRoles` and `accessLevels`?

**Comment by wladston** [comment]
I wonder ... just started out developing a javascript app. Maybe we could dig into code samples for best practices, such as the famous angular/angular-app ?

**Comment by fnakstad** [comment]
I have a fairly good idea of how I want to solve this. But there's definitely a lot of good ideas to pick up from angular-app, so post an issue or send me a pull request if you discover a better way of doing something.
