### ISSUE TITLE
Help with not using jade please

### ISSUE THREAD

**Issue by michaeljoser** [fnakstad/angular-client-side-auth#13]
Hello,

I love this piece of code you wrote and really like that you make it better everytime.

I got one question.. i am not a fan of jade, i prefer pure html.  I'm not having any success modifying the code to just load html rather than jade.

Any tips from you please? would be really appreciated.

**Comment by michaeljoser** [comment]
I kinda found a solution that works for me.

Below i modified routes.js to check for a .html extension for the page i'm requesting. If its an html use sendfile (careful setting the correct path) otherwise render the .jade

```
// file: ./server/routes.js

var routes = [

    // Views
    {
        path: '/partials/*',
        httpMethod: 'GET',
        middleware: [function (req, res) {
            var requestedView;
            if (req.url.substr(-5) === '.html') {  
                // requesting a .html file
                requestedView = path.join(__dirname + '/../client/views/' , req.url);
                res.sendfile(requestedView);
            } else { 
                // its not html, render it as jade
                requestedView = path.join('./' , req.url);
                res.render(requestedView);
            } 
        }],
        accessLevel: accessLevels.public
    },
...
...
```

and in ./client/js/app.js i set the templateUrl to my custom html file

```
// file: ./client/js/app.js
...
...
    $routeProvider.when('/profile',
        {
            templateUrl:    '/partials/profile.html',
            controller:     'ProfileCtrl',
            access:         access.user
        });
...
...
```

With this i can use the default login.jade but serve my other pages as html ..  

dunno if its a best practice though.

**Comment by fnakstad** [comment]
Hi Michael! I guess this depends on if you want to have parts of the application in Jade or have all your views be HTML... I think all you need to do for the latter is to change the "view engine" setting on line 10 in the server.js file to html instead of jade. If you can't get that working, you should be able to do a simple <code>res.sendfile('path/to/view.html')</code>. Let me know if you're still having problems with it!

**Comment by michaeljoser** [comment]
Yes will try that as well. Thanks a lot.

Keep up the good work :)

**Comment by m1ket** [comment]
I'm not a fan of Jade either. How easy do you think it would be to split this into two applications? 1. The Angular JS frontend that runs in Apache and 2. the Node.js server that acts as the API that runs the whole site?

**Comment by fnakstad** [comment]
It shouldn't be too hard I believe, but I don't see the point in using Apache if you also want to use Node.js for the API. If it's just jade that you don't want you can replace it with HTML by changing the view engine settings in Node.
