### ISSUE TITLE
Combined fork with ExpressIO (Express & SocketIO)

### ISSUE THREAD

**Issue by johntom** [fnakstad/angular-client-side-auth#21]
Hi,
Thanks for this great repo, you've solved a piece of the puzzle that's been a bit difficult for me to resolve. To that end I've included credits in my repo which uses another repo plus my dependency on a Firebird Sql database.
John
https://github.com/johntom/Angular-Passport-Auth-SIO

**Comment by fnakstad** [comment]
Awesome! I've been wanting to do some experimentation with SocketIO and Angular, so I'll make sure to check this out :)

**Comment by johntom** [comment]
Note I force app re-load on new login to reset the passport authentication  for socket as nothing else seemed to work. Look forward to your review and I plan to give a lightning demo of this at next angular meetup later this month. I'm also considering the use of sails.js

John

John R. Tomaselli

Greater Than Zero, Inc.

148 West 24th Street

12th Floor

New York, NY 10011

212 989 7385

917 771 3608

**Comment by fnakstad** [comment]
I'm having some trouble getting it to run out of the box, so I have some quick questions before I start hack'n'slashing too much :p
1. At line 1 of [firebird.js](https://github.com/johntom/Angular-Passport-Auth-SIO/blob/master/server/firebird.js) there's an exclamation mark. Was this intended? If so, what is its purpose?
2. server.js has a dependency on a module called express-config that's not installed when running `npm install`. Does that refer to [this repo](https://github.com/blahed/express-config)?

If you don't mind much, I'll fork the project, and see if there's anything I can contribute.

**Comment by johntom** [comment]
Hi,

1) that was a typo. firebird.js represents my attempt to export all the database stuff (mostly works). I've tried to keep the git-hub reference smaller than the my  account and wind up doing cut-n-paste rather than with git commands.

2) In order to get this to work, I tried many different scenarios and I think that left by mistake as it's not in use and I just tested with my app. I've fixed repo.

3) I will help in  whatever way possible as I found your contribution in-valuable.

4) I will try to re-factor a better git-hub sample to I can use the git  commands and not have typos 

5) I will have a few changes tomorrow as I noticed I didn't process the layout and index jade forms properly

I know what what's it like to not have an app work after a download and will try to do a better job.

6) If you want to run with Firebird, I will make you a sample database.

All the best,

John

**Comment by fnakstad** [comment]
Ah, thanks for the reply! I've posted an issue to your repo, so we can just continue the discussion there.

**Comment by johntom** [comment]
HI Frederik,

FYI, in case you missed it, I posted my blog last week and gave a lightning demo at Google. Recently been playing with Sailsjs (version 0.9.3) and put up a little demo at 

https://github.com/johntom/Sails9JadeAngular https://github.com/johntom/Sails9JadeAngular . I think it would be great to have a version of your repo working with sailsjs. While I've given it a brief attempt, I'm not quite up to the skill level and was hoping you might consider porting as I think this would be a great addition.

All the best,

John

Sailsjs

http://sailsjs.org http://sailsjs.org/ 

blog:

http://johntomaselli.blogspot.com/2013/07/firebird-angularjs-node-and-socketio.html http://johntomaselli.blogspot.com/2013/07/firebird-angularjs-node-and-socketio.html 

github

https://github.com/johntom/Angular-Passport-Auth-SIO https://github.com/johntom/Angular-Passport-Auth-SIO

**Comment by fnakstad** [comment]
Hi John! 
Sorry I haven't been able to get back to you. I'm busy preparing a move to Tokyo next month, so I'm up to my ears with stuff I have to get done :) I don't know if I'll have time to get everything up and running with Sails.js, but I'll read your blogpost and try to check out Angular-Passport-Auth-SIO this weekend.

**Comment by johntom** [comment]
No worries and good luck with the move (from where?)

All the best,

John

**Comment by fnakstad** [comment]
Moving to Tokyo from Trondheim, Norway, so there's quite a bit of distance to cover ;)

I've had some time to look at the project today, by the way. I got it up and running pretty fast, and it looks really nice. Good job! Are you using it as the basis for an actual commercial project?

I noticed there were some small bugs, so here are a few suggestions:

For example, when I tried to file a new claim I get an error message in my console saying "Cannot read property 'length' of undefined ... at Object.ClaimCtrl.$scope.postDaily ...". I'm guessing a null object might have been passed into the postDaily() function? I bet it would be really nice if you added some validation to this form.

You're also displaying 'null' for null values in a lot of fields. Maybe it would look better if you simply left the fields blank or printed '-' for null values?

I'm also curious about the "Code" page. What is the purpose of it?

That's just my quick 10 cents :)

**Comment by johntom** [comment]
The system is in pre-production for the web and  the database has been in use for the last 12 years in a  client/server system using Delphi .I just sampled part of the system as a demo and give back to those looking to move into this area. The error you're getting is usually associated with a bad Firebird connection, I will re-test on my end and get back to you. Code form was just there for a different user level route.

John
