### ISSUE TITLE
"Remember me" functionality for social strategies

### ISSUE THREAD

**Issue by Kahramon** [fnakstad/angular-client-side-auth#25]
Hello Frederik,

how are you doing? I see your app is already ready to use in a production software :-) . Good job!

Anyway, I played with the application a bit and I am here to give you some points or questions: as you already implemented "Remember me" functionality for "local strategy" logins, did you consider also this with other strategies like "Facebook", "Twitter" etc.? 
It seems, it does not work now when I checked "Remember Me" while logging via Facebook, I do not know if this is possible to get "Remeber Me" directly from those providers via callbacks. If not, it would be nice some hints how to do it locally within the application. Thank you.

Regards
Kahramon.

**Comment by fnakstad** [comment]
Hi Kahramon! How are you holding up? :)

This might be doable by changing the session cookie time in the callback URL's after a social login redirect. I'll take a look at it and get back to you!

**Comment by Kahramon** [comment]
Hi Frederik, 

thank you for your willingness and commitment! Otherwise it is summer time, everything is fine by me :-) , thanks.

Regards
Kahramon

**Comment by fnakstad** [comment]
Haha, don't worry about it. 
I'm a little busy at right now since I am preparing a move to Tokyo, but I'll get to this as soon as I have the time.
