### ISSUE TITLE
opening http://website/private/test crashes the web interface

### ISSUE THREAD

**Issue by michaeljoser** [fnakstad/angular-client-side-auth#4]
Hello,

I was trying to do something like:

```
    $routeProvider.when('/private/:destination',
```

but angular seems to crash and i cant get the value of $routeParams.destination.  The code for this routing is quite simple but i can't seem to find where its going wrong. any ideas please?

**Comment by fnakstad** [comment]
Good catch! I just committed a fix for this problem: 1bda98f7166d0f1d97aa26ec70f3aae8b3712976
Basically, I was missing a '/' at the beginning of the URL's referring to my local Javascript files and partial views. So, when you tried visiting /private/whatever, it would try fetching Javascript from /private/javascript-file.js and so on.
