### ISSUE TITLE
 error installing express@3.4.1

### ISSUE THREAD

**Issue by ahker** [fnakstad/angular-client-side-auth#42]
how to solve the below issue

root@ahker:~/www/angular-client-side-auth-master# npm start

> angular-client-side-auth@0.0.1 start /home/vinoth/www/angular-client-side-auth
> -master
> node server.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'express'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/vinoth/www/angular-client-side-auth-master/serv
er.js:1:83)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)

npm ERR! angular-client-side-auth@0.0.1 start: `node server.js`
npm ERR! `sh "-c" "node server.js"` failed with 1
npm ERR!
npm ERR! Failed at the angular-client-side-auth@0.0.1 start script.
npm ERR! This is most likely a problem with the angular-client-side-auth package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-client-side-auth
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 3.2.0-55-generic
npm ERR! command "node" "/usr/bin/npm" "start"
npm ERR! cwd /home/vinoth/www/angular-client-side-auth-master
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message angular-client-side-auth@0.0.1 start: `node server.js`
npm ERR! message `sh "-c" "node server.js"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vinoth/www/angular-client-side-auth-master/npm-debug.log
npm not ok
root@ahker:~/www/angular-client-side-auth-master# npm install express
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/connect/2.9.1
npm http GET https://registry.npmjs.org/commander/2.0.0
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/commander/2.0.0
npm http 304 https://registry.npmjs.org/connect/2.9.1
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.1
npm http 304 https://registry.npmjs.org/debug
npm ERR! error installing express@3.4.1
npm ERR! error rolling back express@3.4.1 Error: UNKNOWN, unknown error '/home/v
inoth/www/angular-client-side-auth-master/node_modules/express'

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: connect@2.9.1
npm ERR! Required: {"node":">= 0.8.0"}
npm ERR! Actual:   {"npm":"1.1.4","node":"0.6.12"}
npm ERR!
npm ERR! System Linux 3.2.0-55-generic
npm ERR! command "node" "/usr/bin/npm" "install" "express"
npm ERR! cwd /home/vinoth/www/angular-client-side-auth-master
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm http GET https://registry.npmjs.org/mime
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vinoth/www/angular-client-side-auth-master/npm-debug.log
npm not ok
root@ahker:~/www/angular-client-side-auth-master#

**Comment by jshemas** [comment]
I'm able to run this app using express 3.4.1

Not sure if this helps but, I got it working by running the  following commands...

`git clone https://github.com/fnakstad/angular-client-side-auth`
`npm install`
((Comment out these lines: https://github.com/fnakstad/angular-client-side-auth/blob/master/server.js#L24-L27 ))
`npm start` or `node server.js`

**Comment by fnakstad** [comment]
Thanks jshemas! 
ahker: I tried doing a fresh checkout, and get the same error message if I run `npm start` before `npm install`. Please make sure to run `npm install` first, since this will install the required dependencies. Also provide consumer keys for social logins or comment out the lines jshemas mentioned. This should all be pretty obvius if you check the readme.
