### ISSUE TITLE
"failed to obtain request token" in Twitter

### ISSUE THREAD

**Issue by dailystore** [fnakstad/angular-client-side-auth#47]
When I clicked on the Twitter button to direct to Twitter's login page, It threw the error "failed to obtain request token" instead. I had added the Twitter consumer key and secret yet (The one created in https://dev.twitter.com/apps). The Google works fine. I haven't checked Facebook and Linkedin yet. 

I googled the error and they tell me to change the server's clock, but I'm using windows localhost and my clock still be accurate.

Any help would be appreciated.

![original](https://f.cloud.github.com/assets/4099636/1582513/e6552190-51ef-11e3-8555-34d6dd747b4a.jpg)

**Comment by fnakstad** [comment]
Are you the same person who commented on my blog? I'll leave my reply here as well:
You probably entered the wrong values for your consumer key and secret. Mine work without any problems, but if I change to incorrect values I get the same error message. Maybe you could try confirming that you're using the correct values from your Twitter dashboard?
