### ISSUE TITLE
!!! directive in Jade is now obsolete

### ISSUE THREAD

**Issue by Satyam** [fnakstad/angular-client-side-auth#51]
In `client/views/index.jade` the initial `!!! 5` in the very first line causes an error when the server is started.  It should be replaced by a `doctype` declaration.

**Comment by fnakstad** [comment]
Thanks for reporting this Satyam! I noticed that I hadn't set explicit version numbers for certain packages in `package.json`, including Jade, which caused this error. Should be fixed if you pull the last commits :)
