### ISSUE TITLE
Active Tab not displayed

### ISSUE THREAD

**Issue by berlin2** [fnakstad/angular-client-side-auth#62]
The Active Tab 'Private' is not displayed when selecting /private/nested/ or /private/admin/ on top of the page.

**Comment by fnakstad** [comment]
Ah, you are right! This was a side-effect of switching to ui-sref. I've rolled back those commits now, so it should be working again. I still want to switch to ui-sref, but we will have to wait till there's a way of applying ui-sref-active classes to links associated with parent scopes.

Thanks for reporting!
