### ISSUE TITLE
npm install errors.

### ISSUE THREAD

**Issue by sonisaurabh19** [fnakstad/angular-client-side-auth#74]
Hi,
I have cloned a copy and trying to install. Followed the instructions via REDME.doc to first install bower using "sudo npm install -g bower", this was successful.
But on running "npm install", I get the following errors due to which I do not view anything on "localhost:8000". The "npm test" however is successful with no errors.

Can anyone help please.

/--------------ERROR--------------/
bower angular#~1.2.12                                  ENOTDIR ENOTDIR, mkdir '/var/folders/yw/3s26gp1d4jq6cx4my3cl80lr0000gn/T/saurabhsoni/bower'

Stack trace:
Error: ENOTDIR, mkdir '/var/folders/yw/3s26gp1d4jq6cx4my3cl80lr0000gn/T/saurabhsoni/bower'

Console trace:
Trace
    at StandardRenderer.error (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/q/q.js:808:24)
    at /Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/q/q.js:752:41)
    at /Users/saurabhsoni/Downloads/angular-client-side-auth/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.10.22
OS: Darwin 13.1.0 x64

npm ERR! angular-client-side-auth@0.0.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-client-side-auth@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the angular-client-side-auth package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-client-side-auth
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/saurabhsoni/Downloads/angular-client-side-auth
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/saurabhsoni/Downloads/angular-client-side-auth/npm-debug.log
npm ERR! not ok code 0

Thanks,
Saurabh

**Comment by fnakstad** [comment]
Judging from the error trace it seems like `bower install` is failing... Perhaps something went wrong when installing Bower. Can you try running the command `bower -v` in your terminal, and see if it returns a version number? You could also try to run `bower install`, and see if you get a better error trace from that.

**Comment by sonisaurabh19** [comment]
Sure, i will try bower install. Btw, bower version is:
$ bower -v
1.3.3

Thanks!

**Comment by fnakstad** [comment]
Everything go okay? I'm going ahead and closing this issue, but feel free to reopen if you still can't get it working :)

**Comment by mohiballah** [comment]
plz same problem here

**Comment by fnakstad** [comment]
@mohiballah Did you try following the steps we posted in the comments? If so and you're still having problems, can you post your error trace here?

**Comment by mohiballah** [comment]
C:\angPro\hope\public_html>bower install
bower not-cached    git://github.com/angular/bower-angular-mocks.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular-mocks.git#~1.2.12
bower not-cached    git://github.com/angular-ui/ui-router.git#0.2.8-bowratic-ted
ium
bower resolve       git://github.com/angular-ui/ui-router.git#0.2.8-bowratic-ted
ium
bower not-cached    git://github.com/angular/bower-angular.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular.git#~1.2.12
bower not-cached    git://github.com/angular/bower-angular-cookies.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular-cookies.git#~1.2.12
bower not-cached    git://github.com/FortAwesome/Font-Awesome.git#~4.0.3
bower resolve       git://github.com/FortAwesome/Font-Awesome.git#~4.0.3
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github
.com/angular/bower-angular-cookies.git", exit code of #128

Additional error details:
error: Couldn't resolve host 'github.com' while accessing https://github.com/ang
ular/bower-angular-cookies.git/info/refs?service=git-upload-pack
fatal: HTTP request failed

**Comment by mohiballah** [comment]
seems the problem come from bower-angular-cookies
when i do "bower install" again without making any change , i have this

**Comment by mohiballah** [comment]
C:\angPro\hope\public_html>bower install
bower not-cached    git://github.com/angular/bower-angular.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular.git#~1.2.12
bower not-cached    git://github.com/angular-ui/ui-router.git#0.2.8-bowratic-ted
ium
bower resolve       git://github.com/angular-ui/ui-router.git#0.2.8-bowratic-ted
ium
bower not-cached    git://github.com/angular/bower-angular-cookies.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular-cookies.git#~1.2.12
bower not-cached    git://github.com/angular/bower-angular-mocks.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular-mocks.git#~1.2.12
bower not-cached    git://github.com/FortAwesome/Font-Awesome.git#~4.0.3
bower resolve       git://github.com/FortAwesome/Font-Awesome.git#~4.0.3
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github
.com/FortAwesome/Font-Awesome.git", exit code of #128

Additional error details:
error: Couldn't resolve host 'github.com' while accessing https://github.com/For
tAwesome/Font-Awesome.git/info/refs?service=git-upload-pack
fatal: HTTP request failed

**Comment by mohiballah** [comment]
i do "bower install" 2 times without making any change, says that the problem from 2 deference source

the first : angular-cookie
the secend : Font-Awesome
same in the 3th with other package

**Comment by fnakstad** [comment]
This is a problem with Bower. Most likely it is due to some firewall settings on your machine. Check [this SO thread](http://stackoverflow.com/questions/21789683/howto-fix-bower-ecmderr) for more info.
