### ISSUE TITLE
Login with Google oAuth instead OpenID

### ISSUE THREAD

**Issue by beeva-manueldepaz** [fnakstad/angular-client-side-auth#79]
Hi Frederik,

I'm working on adding a new a passport connector to login in the app with google-plus instead of google. This is due to the fact that the OpenID access it's going to be declared obsolete.

I'm having problems when I try to include the passport strategy on server because it doesn't log the user. It doesn't receive the token params.

I'm using the Angular Google Plus Sign-in Button Directive from https://github.com/sirkitree/angular-directive.g-signin to keep clear the frontend.

Could you help me please?
Thanks in advance.

**Comment by beeva-manueldepaz** [comment]
Finally I found a possible solution:
https://github.com/beeva-manueldepaz/angular-client-side-auth

**Comment by fnakstad** [comment]
Hi there, and so sorry I didn't get to you in time! Glad to see you found the solution though :)
