### ISSUE TITLE
npm install karma issues

### ISSUE THREAD

**Issue by ghost** [fnakstad/angular-client-side-auth#81]
While installing this I get the following error:

 ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.4 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.4 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-chai@0.0.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/***_/Code/angular-client-side-auth
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.15
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/**_*/Code/angular-client-side-auth/npm-debug.log
npm ERR! not ok code 0

my steps were
1. git clone into this repo
2. run npm install
3. run into this error.

I have tried:
1. modifying the package.json
2. reinstalling karma (globally and locally..)
3. reinstalling bower
4. npm update
5. bower update

I'd consider myself a beginner, and I do not know what to try next. Can you help me?

**Comment by jshemas** [comment]
Re-installing the latest karma locally, worked for me. I made a pull request to fix this.

In the mean time, you can just manually update karma:
`npm install karma`

**Comment by fnakstad** [comment]
Just accepted jshemas PR updating Karam version number. Thanks :)
