### ISSUE TITLE
Removing empty files and directories

### ISSUE THREAD

**Issue by Jakobovski** [fnakstad/angular-client-side-auth#84]
There are a bunch of empty files and directories in /client/. Is that intentional? My 2cents is that removing said items will make the repository cleaner and easier to navigate.

If you are interested I will be happy to remove said items and push the changes.

Thanks,
Zohar

**Comment by fnakstad** [comment]
Hi Zohar, and sorry about my extremely slow response. What files and directories specifically are you referring to?

**Comment by Jakobovski** [comment]
I am not sure... I cant seem to find what I was referring to when I made this issue 2 months ago.
