### ISSUE TITLE
Prevent state access when toState.data == undefined 

### ISSUE THREAD

**Issue by Jakobovski** [fnakstad/angular-client-side-auth#85]
An error is thrown in `app.js` on line 142 when `toState.data` is `undefined`. 

Something like this would solve the problem:

``` javascript
if(!("data.access" in toState)){
    $rootScope.error = "Access undefined for this state";
    event.preventDefault();
}
else if (!Auth.authorize(toState.data.access)) {
    $rootScope.error = "Seems like you tried accessing a route you don't have access to...";
    event.preventDefault();

    if(fromState.url === '^') {
        if(Auth.isLoggedIn()) {
            $state.go('user.home');
        } else {
            $rootScope.error = null;
            $state.go('anon.login');
        }
    }
}
```

With approval I would be happy to make the changes and create a merge request.

**Comment by fnakstad** [comment]
Awesome! Thanks for taking the time to create a fix :)
If you send me a pull request I'll accept it right away.

**Comment by Jakobovski** [comment]
Pull request created see https://github.com/fnakstad/angular-client-side-auth/pull/89

**Comment by fnakstad** [comment]
I just merged it. Thanks for taking the time to submit a PR :)

**Comment by bremme** [comment]
I just cloned the repro and no matter what I try I get the: "Oh no! Acces undefined for this state" error. I haven't fully mastered the code yet, so I can't give an explanation of the possible cause. But when I looked at the live demo (http://angular-client-side-auth.herokuapp.com/) I noticed that the following piece:

``` javascript
        if(!("data.access" in toState)){
            $rootScope.error = "Access undefined for this state";
            event.preventDefault();
        }
```

was missing from the app.js. When I removed this piece I was able to fiddle around with the page.

Probably not related, but another thing that I noticed when running the server: 

```
body-parser deprecated urlencoded: explicitly specify "extended: true" for extended parsing server.js:19:20
```

![screenshot from 2014-09-09 17 46 13](https://cloud.githubusercontent.com/assets/6715707/4204565/7977fc70-3838-11e4-8f28-12c61a5be5f5.png)

**Comment by Jakobovski** [comment]
@bremme see https://github.com/fnakstad/angular-client-side-auth/pull/95

**Comment by RAMDdFLEET** [comment]
i integrated my ionic application with ionFB and ran in localhost. i was able to connect to facebook. Then I built android apk and tested in phone. I followed the instructions as mentioned in the documentation for Android. When i hit the Login Button, it says "Object Object" & not connecting to facebook. What could be the problem? help out!!!
