### ISSUE TITLE
Unresolved variable or type routingConfig

### ISSUE THREAD

**Issue by Kamonone** [fnakstad/angular-client-side-auth#87]
I tried to use the clientside part of the project to work with Java REST backend. But I have a trouble

```
var access = routingConfig.accessLevels; in app.js and

    var accessLevels = routingConfig.accessLevels
        , userRoles = routingConfig.userRoles
```

in services.js gives me an error "Unresolved variable or type routingConfig" in my IDE
so the browser doesn't use it.
and submits only send the rememberme POSTDATA

Any tips?

**Comment by Kamonone** [comment]
I guess its the broken html i got from converting the jade files. Could you please post and html version of partials and index.html somewhere?

**Comment by fnakstad** [comment]
The HTML versions can easily be generated from Jade by using Jade's CLI. I did it for the index.jade page, and put the resulting HTML in [this gist](https://gist.github.com/fnakstad/b962093d169fa76ef4cc). Hope this helps you with your problem!
