### ISSUE TITLE
Google Logout

### ISSUE THREAD

**Issue by ravivit9** [fnakstad/angular-client-side-auth#88]
Hi,

Tried Google Login which works great but when I logout within the sample application it doesn't actually logs out of the demo application.

Steps:
1. Click one of the fancy user login (Google) which redirects to google.com authentication page.  After successful login it redirects to the demo application with additional tab menu.
1.  Now visit different tabs which works fine.
2. Now click Logout button which seems to be logging out by redirecting to the demo application login page but when you click again the Google icon in step #1 it doesn't redirect to the google.com authentication page but instead it enters to the demo application main content explained in step #2.  I would expect this action should redirect to google.com authentication page.
3. To actually logout from google account I opened a new tab in chrome browser and clicked actual google user icon on top right corner not within the demo application and clicked logout which logged out successfully.

Thanks for looking into this.

**Comment by ravivit9** [comment]
I haven't tested other logins (FB,LinkedIn and Twitter).

**Comment by fnakstad** [comment]
Hi there!

I can't reproduce any sort of problem with Google logout, so please allow me to clarify a little bit. When logging out it only logs you out of the demo site, it does not log you out of your Google account. Furthermore, if you have logged in once with Google login and allowed the demo site access to your Google account, it won't redirect to Google to ask for permission again after. This is quite standard for social logins.

If I didn't answer your questions or gave bad answers, please let me know :)
