### ISSUE TITLE
"data.access" in toState is always false

### ISSUE THREAD

**Issue by ankitladhania** [fnakstad/angular-client-side-auth#92]
I came up with this issue that no matter what is inside the `data` the value of `data.access in toState` is always returned `false`. The quick fix i came up with was 
`if(!("data" in toState) || !("access" in toState.data)){`

Does anyone face the same problem or its just me?

**Comment by patrickrbc** [comment]
There's already an issue and a pull request related to that.

**Comment by ankitladhania** [comment]
Yes and i have also submitted a pull request for it.
